spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/employee
    username: root
    password: 2002
  jpa:
    database-platform: org.springframework.orm.jpa.vendor.Database.MYSQL
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        globally_quoted_Identifiers: true
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
